appUser=functional_programming_triads_qa_app
dbName=functional_programming_triads_qa
contexts=reference,demo
classpath=tools/liquibase/postgresql-42.7.9.jar
driver=org.postgresql.Driver
default-schema-name=public
search-path=.
